GC Dental/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <label>Assign To</label>
        <picklist>
            <picklistValues>
                <fullName>Abdullah.SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abhik Ghosh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ajay Rao</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amit Bharadwaj</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amol S.Satpute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anil Kumar P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashish das</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bejoy Raj K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhanu Prakash.P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binny George.K.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Devendra Kumar Singh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farukh Tai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ganesh R.Shirsath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harish K V Gowda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ishan Desh Pandae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jayesh Sawant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jitender Bhaskar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joshua Gnanadurai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhusudhan Y E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manoj kumar singh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manoj Telgote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mousum Borah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagaraj S.M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Narasimha Murthy.V.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Naresh Suresh Kamath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navjeet Singh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neelima Kola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nilesh Sharma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nittu Antony</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pankaj Yadav</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/Test_updateOwner.cls
@isTest
public class Test_updateOwner{
static testmethod void testmethod_updateOwner (){

Profile p = [SELECT Id FROM Profile WHERE Name ='National Sales Manager'];

User mu = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = p.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'NSM', 
                           timezonesidkey='Asia/Kolkata', username='gctestm@gmail.com');

insert mu;

Profile mp = [SELECT Id FROM Profile WHERE Name ='Sales Manager'];
        
        User sm = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = mp.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'Manager', 
                           timezonesidkey='Asia/Kolkata', username='gctestex@gmail.com');
        insert sm;
        
MAP<String, String> Usermap = new MAP<string,string>();
Usermap.put(mu.Lastname,mu.id);


Account acc = new Account();
acc.Name = 'bbbbbb';
acc.Phone__c = '9696969695';
acc.Class__c = 'A';
Usermap.put(acc.Owner.Lastname,acc.Owner.id);
acc.Assign_To__c = mu.id;

acc.OwnerId = acc.Assign_To__c;
insert acc;




}

}