GC Dental/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <picklist>
            <controllingField>Billing_State__c</controllingField>
            <picklistValues>
                <fullName>Abohar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achalpur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adilabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adityapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agartala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmadnagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aizawl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ajmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akbarpur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alandur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alappuzha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aligarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allahabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambala Sadar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambattur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambernath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambikapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amravati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amreli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amritsar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amroha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantapur</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clinic_Name__c</fullName>
        <label>Clinic Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/classes/customersearchcontoller.cls
public with sharing class customersearchcontoller{
    /*   
        Author   : G.Shruthi Reddy
        Date     : 23/9/2013
        Version  : 1.0 
    */
    public ApexPages.StandardController controller {get; set;}
    public List<Account> searchResults {get;set;}
    public Account a;
    public string searchByName {get;set;}
    public string searchByCity{get;set;}
    public string searchByPhone{get;set;}
    public string searchByClinicName{get;set;}

    public customersearchcontoller (ApexPages.StandardController controller) {
        this.controller = controller;
        this.a = (Account)controller.getRecord();
        searchResults = new List<Account>();
        searchByName = '';
        searchByCity = '';
        searchByPhone = '';
        searchByClinicName = '';
        
        search();
        
    }
    // fired when the search button is clicked
    public PageReference search()
    {
      
       String QueryString = ' where ';
       IF(searchByName != '') { 
           QueryString += '(Name LIKE  \''+ searchByName +'%\') AND ';        
       }
       IF(searchByCity != ''){
           QueryString += '(Billing_City__c LIKE \'%'+searchByCity +'%\') AND ';
       }
       IF(searchByPhone != ''){
           QueryString += '(Phone__c LIKE \'%'+searchByPhone+'%\') AND ';
       }
       IF(searchByClinicName!= ''){
           QueryString += '(Clinic_Name__c LIKE \'%'+searchByClinicName+'%\') AND ';
       }
         
       String qry;
       if(QueryString.length() > 7){  
           QueryString = QueryString.subString(0,QueryString.lastIndexOf('AND'));
           System.debug('RRRRRRRRRRRR**********************'+QueryString );
           qry = 'select Id,Name,Phone__c,Billing_City__c,Type__c,Clinic_Name__c from Account ' + QueryString;
       }
       else
           qry = 'select Id,Name,Phone__c,Billing_City__c,Type__c,Clinic_Name__c from Account  Order By Name LIMIT 250';
       searchResults = new List<Account>();
       searchResults = Database.query(qry);
       return null;  
       } 
     
}