GC Dental/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <picklist>
            <picklistValues>
                <fullName>Andaman and Nicobar Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dadra and Nagar Haveli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daman and Diu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haryana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Himachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jammu and Kashmir</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jharkhand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnataka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kerala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lakshadweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhya Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meghalaya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mizoram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagaland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orissa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pondicherry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Punjab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rajasthan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sikkim</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <label>Campaign Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deactivation_Date__c</fullName>
        <label>Deactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/Campaign_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign__c</referenceTo>
        <relationshipLabel>Campaign Line Items</relationshipLabel>
        <relationshipName>Campaign_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Campaign Line Items</relationshipLabel>
        <relationshipName>Campaign_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_in__c</fullName>
        <label>Quantity in</label>
        <picklist>
            <picklistValues>
                <fullName>Box</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Each</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign Line Item</label>
    <nameField>
        <label>Campaign Line Item	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/Demo_Product__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demo_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>is_active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Demo Product</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demo Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/Demo_Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Demo_Product__c</fullName>
        <label>Demo Product</label>
        <referenceTo>Demo_Product__c</referenceTo>
        <relationshipLabel>Demo Product Line Items</relationshipLabel>
        <relationshipName>Demo_Product_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Demo Product Line Items</relationshipLabel>
        <relationshipName>Demo_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_in__c</fullName>
        <label>Quantity in</label>
        <picklist>
            <picklistValues>
                <fullName>Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Each</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Demo Product Line Item</label>
    <nameField>
        <label>Demo Product Line Item No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/Sales_Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_in__c</fullName>
        <label>Quantity in</label>
        <picklist>
            <picklistValues>
                <fullName>Each</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Box</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order Line Item</label>
    <nameField>
        <label>Sales Order Line Item name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/SalesOrder__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select only active campaigns.</errorMessage>
            <filterItems>
                <field>Campaign__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>List of Active Campaigns</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Demo_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Demo Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the active demo products.</errorMessage>
            <filterItems>
                <field>Demo_Product__c.is_active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Please select the active demo products.Please start the search with &quot;  D-  &quot;</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Demo_Product__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/Test_salesOrderCon.cls
@isTest
public class Test_salesOrderCon 
{
    static testmethod void Testmethod_salesOrderCon()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name ='Standard User'];

        User u = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = p.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'Manager', 
                           timezonesidkey='Asia/Kolkata', username='gctestm@gmail.com');
        insert u;
        
        Product__c pr = new Product__c(Name='Test product', Product_Price__c=500.00, Product_Code__c='TP');                                          
        insert pr;  
        
        Product__c pr1 = new Product__c(Name='Test product1', Product_Price__c=500.00, Product_Code__c='TP1');                                          
        insert pr1; 
        
        Product__c pr2 = new Product__c(Name='Test product2', Product_Price__c=500.00, Product_Code__c='TP2');                                          
        insert pr2; 
        
        Account a = new Account(Name='Test Customer',Phone__c ='9966565678', Class__c='A', Billing_State__c ='Andhra Pradesh');                 
        insert a;  
        
        system.debug('  Account   '+ a.id);
        
        Date deactivationdate = Date.Today().AddDays(30);
        Date activationdate = Date.Today().AddDays(-1);
              
        Campaign__c camp = new Campaign__c(Name = 'Test Campaign', Activation_Date__c = activationdate , Deactivation_Date__c = deactivationdate , Campaign_Description__c = 'Test Description', isActive__c = TRUE);
        insert camp;
        
        Campaign_Line_Item__c campli = new Campaign_Line_Item__c(Name = 'Test Campaign-{1}',Campaign__c = camp.id, Product__c = pr.id, Quantity__c = 5 ,Product_Price__c = 300.00 , Product_Type__c = 'Paid');
        insert campli;
        
                
        Demo_Product__c demo = new Demo_Product__c(Sales_Executive__c = u.id, From__c = activationdate ,To__c = deactivationdate ,is_active__c = True );
        insert demo;

        Demo_Product_Line_Item__c demoline = new Demo_Product_Line_Item__c(Name = 'Test demo-{1}',Demo_Product__c = demo.id, Product__c = pr.id, Quantity__c = 10, Quantity_in__c = 'Each');
        insert demoline;
              
        Date orderdate = date.today().addDays(1);
        
        SalesOrder__c so = new SalesOrder__c(Customer__c = a.id, Close_Date__c = orderdate, Working_with__c = u.id, Campaign__c = camp.id, Demo_Product__c = demo.id);
        insert so;
        
         system.debug('  SalesOrder   '+ so.id);
        
        Sales_Order_Line_Items__c soli = new Sales_Order_Line_Items__c(Name = 'TestOrder-{1}', SalesOrder__c = so.id, Product__c = pr.id, Order_Quantity__c = 5, Price__c = 1000.00, Quantity_in__c ='Each', Product_From__c = 'Sales Order',UniqueNumber__c=1);
        insert soli;
        
        Sales_Order_Line_Items__c soli1 = new Sales_Order_Line_Items__c(Name = 'TestOrder-{2}', SalesOrder__c = so.id, Product__c = pr1.id, Order_Quantity__c = 5, Price__c = 1000.00, Quantity_in__c ='Each', Product_From__c = 'Campaign Products',UniqueNumber__c=2);
        insert soli1;
        
        Sales_Order_Line_Items__c soli2 = new Sales_Order_Line_Items__c(Name = 'TestOrder-{3}', SalesOrder__c = so.id, Product__c = pr2.id, Order_Quantity__c = 5, Price__c = 1000.00, Quantity_in__c ='Each', Product_From__c = 'Demo Products',UniqueNumber__c=3);
        insert soli2;
        
        Demo_Product__c demo1 = [SELECT ID,Sales_Executive__c,From__c,To__c FROM Demo_Product__c WHERE ID =: demo.id];
        
        
        Date logdate = date.today();
        Task t = new Task(WhatId= a.id, Subject='Visited the Customer',Meeting_Type__c= 'Visited the Customer', ActivityDate = logdate, Sales_Order_No__c = so.name);
        insert t;

        system.runas(u){

            ApexPages.StandardController controller2 = new ApexPages.StandardController(new SalesOrder__c());
            
            apexpages.currentpage().getparameters().put('CF00NN0000000a28i_lkid', a.id);
            salesOrderCon socon = new salesOrderCon(controller2); 

            ApexPages.StandardController controllerD = new ApexPages.StandardController(so);
            salesOrderCon soconD = new salesOrderCon(controllerD); 
                                    
            socon.selecteddemo = demo1;
            socon.AddLineItems();
            socon.deleteSalesOrderLine();
            socon.deletedId = 111;
            socon.deleteSalesOrderLine();
            socon.demoProductRefine();
            
            socon.campaignRefine();
            socon.save();
        }
        
    }
}