GC Dental/src/objects/Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <label>Campaign Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deactivation_Date__c</fullName>
        <label>Deactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/Campaign_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign__c</referenceTo>
        <relationshipLabel>Campaign Line Items</relationshipLabel>
        <relationshipName>Campaign_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Campaign Line Items</relationshipLabel>
        <relationshipName>Campaign_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Campaign Line Item</label>
    <nameField>
        <label>Campaign Line Item	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/Test_campaignCon.cls
@isTest
public class Test_campaignCon 
{
    static testmethod void Testmethod_campaignCon()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name ='Marketing Manager'];

        User u = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = p.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'NSM', 
                           timezonesidkey='Asia/Kolkata', username='gcteste@gmail.com');
        insert u;
        
        Product__c pr = new Product__c(Name='Test product', Product_Price__c=500.00, Product_Code__c='TP');                                          
        insert pr;  
        
        Date deactivationdate = Date.Today().AddDays(30);
        Date activationdate = Date.Today().AddDays(-1);
        
        
        Campaign__c camp = new Campaign__c(Name = 'Test Campaign', Activation_Date__c = activationdate , Deactivation_Date__c = deactivationdate , Campaign_Description__c = 'Test Description', isActive__c = TRUE);
        insert camp;
        
        Campaign_Line_Item__c campli = new Campaign_Line_Item__c(Name = 'Test Campaign-{1}',Campaign__c = camp.id, Product__c = pr.id, Quantity__c = 5 ,Product_Price__c = 300.00);
        insert campli;
        
        system.runas(u){
            ApexPages.StandardController controller = new ApexPages.StandardController(camp);
            campaignCon campcon = new campaignCon(controller); 
            campcon.addMore();
            campcon.deleteCampaignLine();
            campcon.deletedId = 111;
            campcon.deleteCampaignLine();
            campcon.findDuplicate();
            campcon.saveAllRecords();
        }
        
        
    }
}