GC Dental/src/objects/Dealer__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/Primary_Order_Goals_for_manager__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Primary_Order_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Revenue1__c</fullName>
        <label>Target Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Revenue__c</fullName>
        <label>Target Revenue RollUp</label>
        <summarizedField>Primary_Order_Goals_Line_Items__c.Target_Revenue__c</summarizedField>
        <summaryForeignKey>Primary_Order_Goals_Line_Items__c.Primary_Order_Goals_for_manager__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Primary Order Goal</label>
    <nameField>
        <displayFormat>PG-{00000}</displayFormat>
        <label>Primary Order Goals Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Order Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/Primary_Order_Goals_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>Primary Order Goals Line Items</relationshipLabel>
        <relationshipName>Primary_Order_Goals_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Order_Goals_for_manager__c</fullName>
        <label>Primary Order Goal</label>
        <referenceTo>Primary_Order_Goals_for_manager__c</referenceTo>
        <relationshipLabel>Primary Order Goals Line Items</relationshipLabel>
        <relationshipName>Primary_Order_Goals_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue_Generated__c</fullName>
        <label>Revenue Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Revenue__c</fullName>
        <label>Target Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Primary Order Goals Line Item</label>
    <nameField>
        <label>Primary Order Goals Line Items No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Order Goals Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/Test_PrimaryOrdergoalscon.cls
@isTest
public class Test_PrimaryOrdergoalscon{
static testmethod void testmethod_PrimaryOrdergoalscon(){

 Profile p = [SELECT Id FROM Profile WHERE Name ='National Sales Manager'];

        User u = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = p.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'NSM', 
                           timezonesidkey='Asia/Kolkata', username='gcteste@gmail.com');
        insert u;

Profile mp = [SELECT Id FROM Profile WHERE Name ='Sales Manager'];
        
        User sm = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = mp.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'Manager', 
                           timezonesidkey='Asia/Kolkata', username='gctestex@gmail.com');
        insert sm;

Dealer__c deal = new Dealer__c();
deal.Name = 'aaa';
deal.Dealer_Code__c = 'ccc';
deal.Phone__c = '9656989563';
insert deal;
               
Primary_Order_Goals_for_manager__c pog= new Primary_Order_Goals_for_manager__c();
pog.Sales_Manager__c = sm.id;
pog.Start_Date__c = date.newInstance(2013, 11, 11);
pog.End_Date__c = date.newInstance(2014, 11, 11);
pog.Target_Revenue1__c = 1000.00;
insert pog;

SYSTEM.DEBUG('@@@@@@@@@@@@@@@@@@' +pog);

Primary_Order_Goals_Line_Items__c pogline= new Primary_Order_Goals_Line_Items__c();
pogline.Name = 'Test primarygoal-{1}';
pogline.Primary_Order_Goals_for_manager__c = pog.id;
pogline.Dealer__c=deal.id;
pogline.Target_Revenue__c = 100000.00;
pogline.Revenue_Generated__c = 50000.00;
insert pogline;

system.runas(u){
ApexPages.StandardController controller = new ApexPages.StandardController(pog);
PrimaryOrdergoalscon pgcon = new PrimaryOrdergoalscon(controller);
pgcon.addMore();
pgcon.deletegoalLine();
pgcon.saveall();
}

}


}