GC Dental/src/objects/Demo_Product__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demo_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>is_active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Demo Product</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demo Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/Demo_Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Demo_Product__c</fullName>
        <label>Demo Product</label>
        <referenceTo>Demo_Product__c</referenceTo>
        <relationshipLabel>Demo Product Line Items</relationshipLabel>
        <relationshipName>Demo_Product_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Demo Product Line Items</relationshipLabel>
        <relationshipName>Demo_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_in__c</fullName>
        <label>Quantity in</label>
        <picklist>
            <picklistValues>
                <fullName>Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Each</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Demo Product Line Item</label>
    <nameField>
        <label>Demo Product Line Item No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/Test_DemoproductsCon.cls
@isTest
public class Test_DemoproductsCon{
static testmethod void Testmethod_DemoproductsCon(){

Profile p = [SELECT Id FROM Profile WHERE Name ='National Sales Manager'];

User mu = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = p.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'NSM', 
                           timezonesidkey='Asia/Kolkata', username='gctestm@gmail.com');

insert mu;

Profile mp = [SELECT Id FROM Profile WHERE Name ='Sales Manager'];
        
        User sm = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = mp.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'Manager', 
                           timezonesidkey='Asia/Kolkata', username='gctestex@gmail.com');
        insert sm;
        
        
Demo_Product__c demo = new Demo_Product__c();
demo.Sales_Executive__c = sm.id;
demo.From__c = date.newInstance(2013, 11, 11);
demo.To__c = date.newInstance(2014, 11, 11);
demo.is_active__c = True;
insert demo;

Product__c pro = new Product__c();
pro.Name = 'Test product';
pro.Product_Code__c = 'abc';
pro.Product_Price__c = 10.00;
insert pro;

Demo_Product_Line_Item__c demoline = new Demo_Product_Line_Item__c();
demoline.Name = 'Test demo-{1}';
demoline.Demo_Product__c = demo.id;
demoline.Product__c = pro.id;
demoline.Quantity__c = 10;
demoline.Quantity_in__c = 'Each';
insert demoline;

system.runas(mu){
ApexPages.StandardController controller = new ApexPages.StandardController(demo);
DemoproductsCon Dmo = new DemoproductsCon(controller);
Dmo.addMore();
Dmo.deletedemoLine();
Dmo.saveAllRecords();
Dmo.findDuplicate();
}
}
}