GC Dental/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select Executive or Manager to set the Goal.</errorMessage>
            <filterItems>
                <field>User.GC_User_Role__c</field>
                <operation>equals</operation>
                <value>Executive, Manager</value>
            </filterItems>
            <infoMessage>Select Manager or Executive to set the Goal.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/Goal_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Goal Line Items</relationshipLabel>
        <relationshipName>Goal_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Quantity_in__c</fullName>
        <label>Product Quantity in</label>
        <picklist>
            <picklistValues>
                <fullName>Each</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Goal Line Items</relationshipLabel>
        <relationshipName>Goal_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Goal__c</fullName>
        <label>Quantity Goal</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue_Goal__c</fullName>
        <label>Revenue Goal</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Goal Line Item</label>
    <nameField>
        <label>Goal Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_Manager__c</fullName>
        <label>GC Manager</label>
        <relationshipName>GC_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/Test_goalfileuploader.cls
@isTest
public class Test_goalfileuploader
{
    static testmethod void Testmethod_goalfileuploader ()
    {
      
         Profile mp = [SELECT Id FROM Profile WHERE Name ='Sales Manager'];

        User mu = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = mp.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'Manager', 
                           timezonesidkey='Asia/Kolkata', username='gctestm@gmail.com');
        insert mu;
        
        Profile ep = [SELECT Id FROM Profile WHERE Name ='Sales Executive'];

        User eu = new User(alias = 'gctest', email='gctest@gmail.com',emailencodingkey='UTF-8',
                           profileid = ep.Id, lastname='GC Test', languagelocalekey='en_US',
                           localesidkey='en_IN', country='India', GC_User_Role__c = 'Executive', GC_Manager__c = mu.id, 
                           timezonesidkey='Asia/Kolkata', username='gcteste@gmail.com');
        insert eu;
        system.runAs(eu){   
            
            Product__c pr = new Product__c(Name='Test product', Product_Price__c=500.00, Product_Code__c='TP');                                          
            insert pr;  
            
            Date deactivationdate = Date.Today().AddDays(30);
            Date activationdate = Date.Today().AddDays(-1);
            
            Goal__c goa = new Goal__c(Start_Date__c = Date.Today().AddDays(-1)  , End_Date__c = deactivationdate , Sales_Executive__c = eu.id , isActive__c = TRUE);
            insert goa;
            
            Goal_Line_Item__c goali = new Goal_Line_Item__c(Name = 'Test Goal-{1}', Goal__c= goa.id, Product__c = pr.id, Product_Quantity_in__c = 'Each', Quantity_Goal__c = 50 ,Revenue_Goal__c = 30000.00);
            insert goali;
           

        PageReference pageRef = Page.Goalsimport;
        Test.setCurrentPage(pageRef );
        pageRef.getParameters().put('Id', goa.Id);
        goalfileuploader uploadController = new goalfileuploader ();
        
        String dataFromJavaScript = String.valueOf('Username,Start Date,End Date,Product,Quantity Goal,Quantity IN,Revenue Goalaazz11ttt222ggg' +'\n'+ 'gcteste@gmail.com,1/1/2014,31/1/2014,Test product,10000,Each,10000aazz11ttt222ggg'+'\n'+'????:::::******&&&&&&%%%%;;;;TestfileName.csv');        
                   Apexpages.currentPage().getParameters().put('one', dataFromJavaScript );
         string srtr = String.valueOf('Username, Start Date, End Date, Product, Quantity Goal, Quantity IN, Revenue Goal'+ '\n'+ 'gcteste@gmail.com,1/1/2014,31/1/2014,Test product,10000,Each,10000');
                    List<String> parsedCSV= new List<String>();
           
         parsedCSV.add(srtr);
         uploadController.ReadFile();
         uploadController.exportToCSV();
         uploadController.Goalsview();
         uploadController.Importpage();
         
         
         String dataFromJavaScript1 = String.valueOf('Username,Start Date,End Date,Product,Quantity Goal,Quantity IN,Revenue Goalaazz11ttt222ggg' +'\n'+ 'gcteste@gmail.com,1/1/2014,31/1/2014,Test product,10000,Each,10000aazz11ttt222ggg'+'\n'+'????:::::******&&&&&&%%%%;;;;TestfileName.xlsx');        
                   Apexpages.currentPage().getParameters().put('one', dataFromJavaScript1 );
         string srtr1 = String.valueOf('Username, Start Date, End Date, Product, Quantity Goal, Quantity IN, Revenue Goal'+ '\n'+ 'gcteste@gmail.com,1/1/2014,31/1/2014,Test product,10000,Each,10000');
                    List<String> parsedCSV1= new List<String>();
                    parsedCSV1.add(srtr1);
         uploadController.ReadFile();
         uploadController.exportToCSV();
         uploadController.Goalsview();
         uploadController.Importpage();
         
         String dataFromJavaScript2 = String.valueOf('Username,Start Date,End Date,Product,Quantity Goal,Quantity IN,Revenue Goalaazz11ttt222ggg' +'\n'+ 'gcteste@gmail.com,1/1/2014,31/1/2014,Test product1,12se43,Each,10000aazz11ttt222ggg'+'\n'+'????:::::******&&&&&&%%%%;;;;TestfileName.csv');        
                   Apexpages.currentPage().getParameters().put('one', dataFromJavaScript2);
         string srtr2 = String.valueOf('Username, Start Date, End Date, Product, Quantity Goal, Quantity IN, Revenue Goal'+ '\n'+ 'gcteste@gmail.com,1/1/2014,31/1/2014,Test product1,12se43,Each,10000');
                    List<String> parsedCSV2= new List<String>();
                    parsedCSV2.add(srtr2);
         uploadController.ReadFile();
         uploadController.exportToCSV();
         uploadController.Goalsview();
         uploadController.Importpage();
         
         

   
        }
        
        
        
    }
}