GC Dental/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select Executive or Manager to set the Goal.</errorMessage>
            <filterItems>
                <field>User.GC_User_Role__c</field>
                <operation>equals</operation>
                <value>Executive, Manager</value>
            </filterItems>
            <infoMessage>Select Manager or Executive to set the Goal.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GC Dental/src/objects/Goal_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Achieved_Quantity_Goal__c</fullName>
        <label>Achieved Quantity Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Achieved_Revenue__c</fullName>
        <label>Achieved Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Goal Line Items</relationshipLabel>
        <relationshipName>Goal_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Quantity_in__c</fullName>
        <label>Product Quantity in</label>
        <picklist>
            <picklistValues>
                <fullName>Each</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Goal Line Items</relationshipLabel>
        <relationshipName>Goal_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Goal__c</fullName>
        <label>Quantity Goal</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue_Goal__c</fullName>
        <label>Revenue Goal</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UniqueName__c</fullName>
        <label>UniqueName</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Goal Line Item</label>
    <nameField>
        <label>Goal Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GC Dental/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>Luting GIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restorative GIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Composite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Impressioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity_in_each_box__c</fullName>
        <label>Quantity in each box</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>GC_User_Role__c</fullName>
        <label>GC User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Andaman and Nicobar Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dadra and Nagar Haveli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daman and Diu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haryana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Himachal Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jammu and Kashmir</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jharkhand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnataka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kerala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lakshadweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhya Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meghalaya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mizoram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagaland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orissa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pondicherry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Punjab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rajasthan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sikkim</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

GC Dental/src/classes/goalCon.cls
public with sharing class goalCon {
 
 /*   
    Author   : Naga Mallikarjuna Rao
    Date     : 18/09/2013
    Version  : 1.0 
 */
    
    public MAP<Id, String> findDupUser{get; set;}
    
    public goal__c goalRecord{get; set;}
    public LIST<Goal_Line_Item__c> goalsLineItems{get; set;}
    public MAP<Decimal , Goal_Line_Item__c> goalsLineItemsMAP{get; set;}
    
    public LIST<Product__c> allProducts{get; set;}
    public List<SelectOption> picklistValues{get; set;}  
    public MAP<String, String> findDupProducts{get; set;}
    
    public Id MasterId{get;set;}
    public Integer uniqueNo{get;set;}
    public String errorMessage{get;set;}
    public Decimal deletedId{get;set;}
    public LIST<ID> removeDup{get; set;} 
    
    public List<SelectOption> ChoosenUser{get;set;}
    public String SelectedUser{get;set;}
    public User LoggedinUser{get;set;}
    
    public goalCon(ApexPages.StandardController controller) {
        goalRecord = new goal__c();
        goalsLineItems = new LIST<Goal_Line_Item__c>();
        goalsLineItemsMAP = new MAP<Decimal , Goal_Line_Item__c>();
         
        allProducts = new LIST<Product__c>();
        picklistValues = new List<SelectOption>();
        findDupProducts = new MAP<String, String>();
        findDupUser  = new MAP<Id, String>();
        
        
        // Mahesh Edit start
        
        LoggedInuser = new User();
        LoggedInuser = [SELECT Id, Name, Username, Email, GC_User_Role__c,UserRoleId, State__c, Manager.Id FROM User WHERE Id =: UserInfo.getUserId() AND isActive =: TRUE];

        SET<ID> UserRolesUnderManager = new SET<ID>();    
        SET<ID> loginUserRollId = new SET<ID>();
        User ForUserRoleID = new User();
        
        ForUserRoleID = [SELECT Id,UserRoleId, Name, Email, UserName FROM User WHERE Id=: UserInfo.getUserId() AND isActive =: TRUE ORDER BY Name ];    
         
        loginUserRollId.add(ForUserRoleID.UserRoleId); 
        
        UserRolesUnderManager.add(ForUserRoleID.UserRoleId);
        UserRolesUnderManager.addAll(getAllSubRoleIds(loginUserRollId));
        
        MAP<Id,User> managerListMap = new MAP<Id,User>([SELECT ID, Name, Email, UserName FROM USER WHERE isActive =: TRUE AND (GC_User_Role__c = 'Manager' OR GC_User_Role__c = 'Executive') AND UserRoleID IN: UserRolesUnderManager ORDER BY Name]);
             
        deletedGoalLineItems = new LIST<Decimal>();
        uniqueNo = 1;
        
        this.goalRecord= (goal__c )Controller.getRecord();
        removeDup = new LIST<ID>();
        
        if(null != Controller.getId()){
        
             MasterId = Controller.getId();
             goalRecord = [SELECT ID, NAME,End_Date__c,Start_Date__c,Sales_Executive__c, isActive__c FROM Goal__c WHERE id=: Controller.getId() ];
            
                removeDup.add(goalRecord.id);
            
             for(Goal_Line_Item__c glp: [SELECT  g.Id, g.Revenue_Goal__c, g.Quantity_Goal__c, g.Product__c, g.Product_Quantity_in__c,g.Name, g.Goal__c, g.Achieved_Revenue__c, g.Achieved_Quantity_Goal__c,g.UniqueName__c From Goal_Line_Item__c g WHERE Goal__c=: Controller.getId()]){
                 glp.UniqueName__c =  uniqueNo;
                 
                 goalsLineItemsMAP.put(glp.UniqueName__c , glp);
                 
                 uniqueNo++;
             }
              
             goalsLineItems.addAll(goalsLineItemsMAP.values());
             // [SELECT  g.Id, g.Revenue_Goal__c, g.Quantity_Goal__c, g.Product__c, g.Product_Quantity_in__c, g.Name, g.Goal__c, g.Achieved_Revenue__c, g.Achieved_Quantity_Goal__c From Goal_Line_Item__c g WHERE Goal__c=: Controller.getId()]; 
        }
        
        LIST<User> userslist = new List<user>();
        userslist.addAll(managerListMap.values());
        userslist.sort();
        
        ChoosenUser = new LIST<SelectOption>(); 
        ChoosenUser.add(new SelectOption('None', '--None--')); 
        
        for(User u: userslist){
            ChoosenUser.add(new SelectOption(u.Id, U.Name));
            SelectedUser = goalRecord.Sales_Executive__c;
        }
        
        
        allProducts = [Select   p.Quantity_in_each_box__c, p.Product_Price__c, p.Product_Family__c, p.Product_Description__c, p.Product_Code__c, p.Name,  p.Id  From Product__c p ORDER BY p.Name];

        if(UserInfo.getOrganizationId() == '00DN00000003jpSMAQ'){
           picklistValues.add(new SelectOption('a06N0000000u123456', '--None--'));
        }
        else{
           picklistValues.add(new SelectOption('a089000000Mg123456', '--None--')); 
        }
        
        for(Product__c pr :allProducts ){
           picklistValues.add(new SelectOption(pr.id, pr.name));  
        }
       
       for(Goal__c gol: [SELECT ID, NAME, End_Date__c,Start_Date__c,Sales_Executive__c, Sales_Executive__r.LastName, isActive__c FROM Goal__c WHERE isActive__c =: TRUE AND ID NOT IN: removeDup  ]){
               findDupUser.put(gol.Sales_Executive__c , gol.Sales_Executive__r.LastName);
       }

    }
    
    
    public void addMore(){
        
        findDupProducts = new Map<String, String>();
        errorMessage = '';
         
        for(Goal_Line_Item__c glb: goalsLineItems){          
            if(glb.Product__c != null){
                if(findDupProducts.containsKey(glb.Product__c)){
                     errorMessage = 'Error: Duplicate product found, please change the product';
                }
                else{    
                     findDupProducts.put(glb.Product__c, glb.Product__c);
                }
            } 
           if(glb.Product__c == 'a06N0000000u123456' || glb.Product__c == 'a089000000Mg123456'){
               errorMessage = 'Error: Please select the product from picklist.';
           }           
        }

        if(errorMessage == ''){    
           
            Goal_Line_Item__c gl = new Goal_Line_Item__c();
            gl.Goal__c = MasterId;
            gl.UniqueName__c =  uniqueNo;
            uniqueNo++;
            gl.Product_Quantity_in__c = 'Each';
               
            goalsLineItems.add(gl);
            goalsLineItemsMAP.put(gl.UniqueName__c , gl);
        }
    }
  
   
    public LIST<Decimal> deletedGoalLineItems{get; set;}
   
    public void deleteGoalLine(){
        
      String  del = apexpages.currentpage().getparameters().get('deletedId');

      if( null != del){
          deletedId = Decimal.valueOf(del);
      }
      
      deletedGoalLineItems.add(deletedId);
      
      if(deletedId != null){ 
          goalsLineItemsMAP.remove(deletedId);
      
          goalsLineItems = new LIST<Goal_Line_Item__c>();
          goalsLineItems.addAll(goalsLineItemsMAP.values());
      }
      
    }
    
    public PageReference saveAllRecords(){
    
        PageReference reference;
        findDuplicate(); 
        
        if(goalRecord.Start_Date__c >= goalRecord.End_Date__c){
            errorMessage = 'Error: End date must be greater than Start date';            
        }
        
        if(goalsLineItems.size() <= 0){
            errorMessage = 'Error: Please add atleast one product to set the Goal.';
        }

       if(errorMessage =='' ){
       
           goalRecord.Sales_Executive__c = SelectedUser;
            if( goalRecord.OwnerId != null){
                 goalRecord.OwnerId = SelectedUser;
             }else If(goalRecord.OwnerId != SelectedUser ){
                 goalRecord.OwnerId = SelectedUser;
             }

           Database.upsertResult res =  DataBase.Upsert( goalRecord, false);
            
           if(res.isSuccess()){
            
               goal__c goal = [SELECT Id, Name FROM goal__c WHERE ID =: res.getId()];
                
              //  deletedGoalLineItems
                LIST<Goal_Line_Item__c> goTodeletGoalLineItems = [SELECT  g.Id, g.Revenue_Goal__c, g.Quantity_Goal__c, g.Product__c, g.Product_Quantity_in__c,g.Name, g.Goal__c, g.Achieved_Revenue__c, g.Achieved_Quantity_Goal__c,g.UniqueName__c From Goal_Line_Item__c g WHERE Goal__c=: res.getId()  AND UniqueName__c IN: deletedGoalLineItems];
                DataBase.delete(goTodeletGoalLineItems ,false);
                
                for(Goal_Line_Item__c gli: goalsLineItems){
                    
                    
                    if(gli.Product__c == 'a06N0000000u123456' || gli.Product__c == 'a089000000Mg123456'){
                        errorMessage = 'Error: Please select the product from picklist.';
                        
                    }
                    
                    if(gli.Name == null){
                        gli.Name = goal.Name +'-{'+ gli.UniqueName__c +'}';
                    }
                    
                    if(gli.Goal__c == null){
                        gli.Goal__c = res.getId();
                    }
                    
                }
                if(errorMessage == ''){ 
  
                    DataBase.Upsert( goalsLineItems , false);
                                                        
                    reference=new PageReference('/'+res.getId());
                    reference.setRedirect(true);
                }   

            }
        }
        else{
        }
        return reference;      
    }
    
    
    
    public void findDuplicate(){
        
          findDupProducts = new Map<String, String>();
          errorMessage ='';
          
         for(Goal_Line_Item__c gli: goalsLineItems ){
             
             if(findDupProducts.containsKey(gli.Product__c)){
                 errorMessage = 'Error: Duplicate product found, please change the product.';
             }else{    
                 findDupProducts.put(gli.Product__c, gli.Product__c);
                  
             }
         }
         
         findDupUser = new MAP<Id, String>();
   
         for(Goal__c gol: [SELECT ID, NAME, End_Date__c,Start_Date__c,Sales_Executive__c, Sales_Executive__r.LastName, isActive__c 
                                 FROM Goal__c WHERE isActive__c =: TRUE AND Sales_Executive__c =: goalRecord.Sales_Executive__c AND ID NOT IN: removeDup AND End_Date__c >: goalRecord.Start_Date__c ]){      
               findDupUser.put(gol.Sales_Executive__c , gol.Sales_Executive__r.LastName);
         }  
         if(findDupUser.containsKey(goalRecord.Sales_Executive__c)){
          //   errorMessage += '<br/> Sales Executive had the goal for this month Please contact Administrator';
         }
    }
    
    public SET<ID> getAllSubRoleIds(Set<ID> roleIds){
        SET<ID> currentRoleIds = new SET<ID>();
        
        for(UserRole userRole :[SELECT Id FROM UserRole WHERE ParentRoleId 
                                IN :roleIds AND ParentRoleID != null])
        currentRoleIds.add(userRole.Id); 
        if(currentRoleIds.size() > 0)
            currentRoleIds.addAll(getAllSubRoleIds(currentRoleIds)); 
        return currentRoleIds;
    }  
    
}